version: '2'
services:
  webui:
    build:
      context: ../
      dockerfile: _docker/Dockerfile.webui
    ports:
      - "35729:35729"
      - "8080:8080"
      - "${PORT_HTTPS_WEBUI}:${PORT_HTTPS_WEBUI}"
    volumes:
      - ./../webui:/app
      - "./conf/.gitconfig-container:/root/.gitconfig"
      - "./conf/self-signed.dev.cert:/root/self-signed.dev.cert"
      - "./conf/self-signed.dev.key:/root/self-signed.dev.key"
    command: "npm start"
    environment:
      - "HTTPS_PORT=${PORT_HTTPS_WEBUI}"

  api_proxy:
    image: nginx:1.11.4-alpine
    ports:
      - "3000:80"
      - "${PORT_HTTPS_API}:443"
    volumes:
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./conf/nginx/nginx.conf.cors_headers:/etc/nginx/nginx.conf.cors_headers:ro"
      - "./conf/self-signed.dev.cert:/etc/ssl/certs/self-signed.dev.cert"
      - "./conf/self-signed.dev.key:/etc/ssl/private/self-signed.dev.key"
    networks:
      - apinet
    depends_on:
      - api

  api:
    build:
      context: ../
      dockerfile: _docker/Dockerfile.api
    volumes:
      - ./../api:/app
    networks:
      - apinet
    command: "./node_modules/.bin/pm2-docker /app/pm2process.yml"
    environment:
      RETHINK_HOST: rdb
      NODE_ENV: "${NODE_ENV}"
    env_file:
      - ../aws-creds.ignore.env
    depends_on:
      - rdb

  jobqueue:
    build:
      context: ../
      dockerfile: _docker/Dockerfile.jobqueue
    volumes:
      - ./../jobqueue:/app
    networks:
      - apinet
    command: "./node_modules/.bin/pm2-docker /app/pm2process.yml"
    environment:
      RETHINK_HOST: rdb
      NODE_ENV: "${NODE_ENV}"
    env_file:
      - ../aws-creds.ignore.env
    depends_on:
      - rdb

  rdb:
    image: jlhawn/rethinkdb:2.3.5
    volumes:
      - ./.rethink-data/rdb:/var/data
    networks:
      apinet:
      dbnet:
        aliases:
          - rdb.1
    ports:
      - "8081:8080"
    command: "--bind all --canonical-address rdb.1 --directory /var/data/rethinkdb"

networks:
  apinet:
    external: false
  dbnet:
    external: false
